### ISSUE TITLE
Start addon issue

### ISSUE THREAD

**Issue by CWlf** [NeverWise/plugin.video.virginradio.it#2]
Hi,
when I try to start "Virgin Radio Italia" Kodi tell me there is an error  (View Log for more information). :(

I have 1.0.6 version.

kodi.log:

`11:02:49 T:18446744071956754944   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('data-original',)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.virginradio.it/default.py", line 130, in <module>
                                                vr = VirginRadio()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.virginradio.it/default.py", line 35, in __init__
                                                img = self._makeUrl(video.a.img['data-original']).replace('206/122', '600/315')
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.beautifulsoup/lib/BeautifulSoup.py", line 613, in __getitem__
                                                return self._getAttrMap()[key]
                                            KeyError: ('data-original',)
                                            -->End of Python script error report<--
11:02:49 T:18446744072443960576   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.virginradio.it/?content_type=video
11:02:49 T:18446744072443960576   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.virginradio.it/?content_type=video) failed
11:02:59 T:18446744071956754304   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('data-original',)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.virginradio.it/default.py", line 130, in <module>
                                                vr = VirginRadio()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.virginradio.it/default.py", line 35, in __init__
                                                img = self._makeUrl(video.a.img['data-original']).replace('206/122', '600/315')
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.beautifulsoup/lib/BeautifulSoup.py", line 613, in __getitem__
                                                return self._getAttrMap()[key]
                                            KeyError: ('data-original',)
                                            -->End of Python script error report<--
11:02:59 T:18446744072443960576   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.virginradio.it/?content_type=video
11:02:59 T:18446744072443960576   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.virginradio.it/?content_type=video) failed
11:03:09 T:18446744071956755584   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('data-original',)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.virginradio.it/default.py", line 130, in <module>
                                                vr = VirginRadio()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.virginradio.it/default.py", line 35, in __init__
                                                img = self._makeUrl(video.a.img['data-original']).replace('206/122', '600/315')
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.beautifulsoup/lib/BeautifulSoup.py", line 613, in __getitem__
                                                return self._getAttrMap()[key]
                                            KeyError: ('data-original',)
                                            -->End of Python script error report<--
11:03:09 T:18446744072443960576   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.virginradio.it/?content_type=video
11:03:09 T:18446744072443960576   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.virginradio.it/?content_type=video) failed
11:03:31 T:18446744071895260800   ERROR: EXCEPTION: Non-Existent Control 1
11:03:34 T:18446744072006460416 WARNING: Attempt to use invalid handle -1`

**Comment by NeverWise** [comment]
Can you try the newer version 1.0.7?
You can find the newer version on my repository at this url: https://github.com/NeverWise/repository.neverwise-storage/raw/master/addons/repository.neverwise/repository.neverwise-1.0.0.zip

**Comment by CWlf** [comment]
Repository installed!
Thank you, good job; now it work perfectly. Also "La Cosa" and D-Play work very good!
